readme_index:
  with_frontmatter: true

plugins:
  - jekyll-relative-links
  - jemoji
  - jekyll-avatar
  - jekyll-mentions
  - jekyll-paginate
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

relative_links:
  enabled: true
  collections: true

remote_theme: rundocs/jekyll-rtd-theme
theme: null
syntax_highlighter_style: colorful

translate:
  # shortcodes
  danger:
  note:
  tip:
  warning:
  # 404
  not_found:
  # copyright
  revision:
  # search
  searching:
  search:
  search_docs:
  search_results:
  search_results_found: # the "#" in this translate will replaced with results size!
  search_results_not_found:

exclude:
  - README.md
  - LICENSE.md
  - Makefile
  - CMakeLists.txt
  - CNAME
  - LICENSE
  - update.sh
  - Gemfile
  - Gemfile.lock
  - requirements.txt
  - build
  - src
  - libuv
  - coroutine-built
  - pthreads4w
  - .github
  - valgrind.supp
  - package.json
  - package-lock.json
  - webpack.config.js
  - jekyll-rtd-theme.gemspec
