plugins:
  - jekyll-relative-links
  - jemoji
  - jekyll-avatar
  - jekyll-mentions

relative_links:
  enabled: true
  collections: true

remote_theme: rundocs/jekyll-rtd-theme
syntax_highlighter_style: colorful

exclude:
  - README.md
  - LICENSE.md
  - Makefile
  - CMakeLists.txt
  - CNAME
  - LICENSE
  - update.sh
  - Gemfile
  - Gemfile.lock
  - requirements.txt
  - build
  - src
  - libuv
  - coroutine-built
  - pthreads4w
  - .github
  - valgrind.supp
  - package.json
  - package-lock.json
  - webpack.config.js
  - jekyll-rtd-theme.gemspec
