name: armv7, aarch64, ppc64le

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-qemu:
    name: ${{ matrix.target }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: arm
            arch: armv7
          - target: aarch64
            arch: aarch64
          - target: ppc64v2
            arch: ppc64le
    steps:
      - uses: actions/checkout@v3
      - uses: uraimo/run-on-arch-action@v2
        with:
          arch: ${{ matrix.arch }}
          distro:  ubuntu_latest
          install: |
            apt-get update -q -y
            apt-get install -q -y --no-install-recommends cmake build-essential
          env: |
            # Valgrind on arm will fail if the stack size is larger than 8MB.
            # Set QEMUs stack size to 8MB since Github runners use 16MB default.
            QEMU_STACK_SIZE: 8388608
          run: |
            mkdir build
            cd build
            cmake -DCMAKE_BUILD_TYPE=Debug -DBUILD_TESTING=ON ..
            cmake --build .
            ./chan_3
            ./primes
            ./test_delay 2
            ./go_channel
            ./go_sleep
            ./go_select
            if [ "${{ matrix.target }}" != "arm" ]; then
                ./go_wait_group
                ./go_panic
            fi
            ./co_call_uv
            ./co_cpp_future_wait
            ./test_map
            ./test_reflect
